generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Story
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          story
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Carnets d'expéditions et photographies
        display: [=title]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~