<?php

/**
 * BaseStoryPlace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Stories
 * 
 * @method string              getTitle()   Returns the current record's "title" value
 * @method Doctrine_Collection getStories() Returns the current record's "Stories" collection
 * @method StoryPlace          setTitle()   Sets the current record's "title" value
 * @method StoryPlace          setStories() Sets the current record's "Stories" collection
 * 
 * @package    lat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoryPlace extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_place');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Story as Stories', array(
             'local' => 'id',
             'foreign' => 'story_place_id'));
    }
}