<?php

/**
 * BasePublication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property int $type
 * @property string $cover
 * @property string $description
 * @property timestamp $published_at
 * 
 * @method string      getTitle()        Returns the current record's "title" value
 * @method int         getType()         Returns the current record's "type" value
 * @method string      getCover()        Returns the current record's "cover" value
 * @method string      getDescription()  Returns the current record's "description" value
 * @method timestamp   getPublishedAt()  Returns the current record's "published_at" value
 * @method Publication setTitle()        Sets the current record's "title" value
 * @method Publication setType()         Sets the current record's "type" value
 * @method Publication setCover()        Sets the current record's "cover" value
 * @method Publication setDescription()  Sets the current record's "description" value
 * @method Publication setPublishedAt()  Sets the current record's "published_at" value
 * 
 * @package    lat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('publication');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'int', 1, array(
             'type' => 'int',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('cover', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('published_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}