<?php

/**
 * BaseJourney
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $place
 * @property string $file
 * @property string $cover
 * @property timestamp $from_date
 * @property timestamp $to_date
 * @property int $season
 * 
 * @method string    getTitle()     Returns the current record's "title" value
 * @method string    getPlace()     Returns the current record's "place" value
 * @method string    getFile()      Returns the current record's "file" value
 * @method string    getCover()     Returns the current record's "cover" value
 * @method timestamp getFromDate()  Returns the current record's "from_date" value
 * @method timestamp getToDate()    Returns the current record's "to_date" value
 * @method int       getSeason()    Returns the current record's "season" value
 * @method Journey   setTitle()     Sets the current record's "title" value
 * @method Journey   setPlace()     Sets the current record's "place" value
 * @method Journey   setFile()      Sets the current record's "file" value
 * @method Journey   setCover()     Sets the current record's "cover" value
 * @method Journey   setFromDate()  Sets the current record's "from_date" value
 * @method Journey   setToDate()    Sets the current record's "to_date" value
 * @method Journey   setSeason()    Sets the current record's "season" value
 * 
 * @package    lat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJourney extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('journey');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('place', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cover', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('from_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('to_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('season', 'int', 1, array(
             'type' => 'int',
             'notnull' => true,
             'default' => 1,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}