<?php

/**
 * BaseInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $subtitle
 * @property string $image
 * @property string $link
 * @property boolean $is_published
 * 
 * @method string  getTitle()        Returns the current record's "title" value
 * @method string  getSubtitle()     Returns the current record's "subtitle" value
 * @method string  getImage()        Returns the current record's "image" value
 * @method string  getLink()         Returns the current record's "link" value
 * @method boolean getIsPublished()  Returns the current record's "is_published" value
 * @method Info    setTitle()        Sets the current record's "title" value
 * @method Info    setSubtitle()     Sets the current record's "subtitle" value
 * @method Info    setImage()        Sets the current record's "image" value
 * @method Info    setLink()         Sets the current record's "link" value
 * @method Info    setIsPublished()  Sets the current record's "is_published" value
 * 
 * @package    lat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('info');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subtitle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}