place:
  class: sfDoctrineRouteCollection
  options:
    model:                Place
    module:               place
    prefix_path:          /place
    column:               id
    with_wildcard_routes: true

story_place:
  class: sfDoctrineRouteCollection
  options:
    model:                StoryPlace
    module:               place
    prefix_path:          /place
    column:               id
    with_wildcard_routes: true

journey:
  class: sfDoctrineRouteCollection
  options:
    model:                Journey
    module:               journey
    prefix_path:          /journey
    column:               id
    with_wildcard_routes: true

story:
  class: sfDoctrineRouteCollection
  options:
    model:                Story
    module:               story
    prefix_path:          /story
    column:               id
    with_wildcard_routes: true

homepage:
  url:   /
  param: { module: default, action: index }