<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/01 03:58:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=lat',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
