<?php

/**
 * Journey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Journey extends BaseJourney
{
    const SEASON_SUMMER = 1;
    const SEASON_AUTUMN = 2;
    const SEASON_WINTER = 3;
    const SEASON_SPRING = 4;

    static $seasons = array(
        self::SEASON_SUMMER => 'Été',
        self::SEASON_AUTUMN => 'Automne',
        self::SEASON_WINTER => 'Hiver',
        self::SEASON_SPRING => 'Printemps',
    );
}
