<?php

/**
 * JourneyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JourneyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JourneyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Journey');
    }

    public function getBySeason()
    {
        $results = $this->createQuery()
            ->fetchArray();

        $seasons = array();

        foreach ($results as $result) {
            if(array_key_exists($result['season'], $seasons)) {
                array_push($seasons[$result['season']], $result);
            } else {
                $seasons[$result['season']][0] = $result;
            }
        }

        return $seasons;
    }
}