<?php

/**
 * JourneyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JourneyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JourneyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Journey');
    }

    public function getBySeason()
    {
        $results = $this->createQuery()
            ->orderBy("from_date")
            ->where("is_published = ?", true)
            ->execute();

        $journeys = array();

        foreach ($results as $journey) {

            $y = date('Y', time($journey->getFromDate()));

            if(!isset($journeys[$y][$journey->getSeason()])) {
                $journeys[$y][$journey->getSeason()] = array();
            }

            array_push($journeys[$y][$journey->getSeason()], $journey);
        }

        return $journeys;
    }
}