<?php

/**
 * PublicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Publication');
    }
}