<?php

/**
 * Story
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lat
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Story extends BaseStory
{
    const TYPE_PHOTO = 0;
    const TYPE_EXPE = 1;

    static $types = array(
        self::TYPE_PHOTO => 'Photographies',
        self::TYPE_EXPE => 'Carnets',
    );
}
