<?php

/**
 * StoryPlaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoryPlaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StoryPlaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StoryPlace');
    }
}