generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Place
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          place
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title:
          label: Titre
      list:
        title: Voyages en partances
        display: [=title]
        object_actions:
          _edit:
            label: Modifier
          _delete:
            label: Supprimer
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
