# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=lat
      username: root
      password: 

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=lat_test
      username: lat
      password: shieGhoghthunnayryactUgyu

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=lat;dbname=lat
      username: lat
      password: shieGhoghthunnayryactUgyu
