<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('logbook', 'pos_x', 'int', '5', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('logbook', 'pos_y', 'int', '5', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('logbook', 'pos_x');
        $this->removeColumn('logbook', 'pos_y');
    }
}