<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('journey', 'description', 'string', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('journey', 'description');
    }
}