<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('journey', 'file');
        $this->addColumn('journey', 'doc', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('journey', 'file', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->removeColumn('journey', 'doc');
    }
}