<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/31 05:49:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=lat',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
