#  Stories -------

Story:
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [title]
  columns:
    title:          { type: string(255), notnull: true }
    type:           { type: int(1), notnull: true, default: 0 }
    is_published:   { type: boolean, notnull: true, default: 0 }
    started_at:     { type: timestamp, notnull: true }
    ended_at:       { type: timestamp, notnull: true }
    cover:          { type: string(255), notnull: true }
    content:        { type: string(), notnull: true }
    place_id:       { type: integer, notnull: true }
    #localisation of the story on homepage map
    pos_x:          { type: int(5), notnull: true, default: 0 }
    pos_y:          { type: int(5), notnull: true, default: 0 }
  relations:
    Place:
      foreignAlias: Stories

Place:
  columns:
    title:          { type: string(255), notnull: true }

#  Journeys -------

Journey:
  columns:
    title:          { type: string(255), notnull: true }
    is_published:   { type: boolean, notnull: true, default: 0 }
    place_id:       { type: integer, notnull: true }
    doc:           { type: string(255), notnull: true }
    cover:          { type: string(255), notnull: true }
    from_date:      { type: timestamp, notnull: true }
    to_date:        { type: timestamp, notnull: true }
    season:         { type: int(1), notnull: true, default: 1 }
  relations:
    Place:
      foreignAlias: Journeys

#  Publication -------

Publication:
  actAs:
    Sluggable:
      fields: [title]
      unique: true
      canUpdate: true
    Timestampable: ~
  columns:
    title:          { type: string(255), notnull: true }
    type:           { type: int(1), notnull: true, default: 0 }
    cover:          { type: string(255), notnull: true }
    description:    { type: string(255), notnull: true }
    published_at:   { type: timestamp, notnull: true }